title: "Wen-Yuan (Dennis) Ting"
name: "Wen-Yuan Ting"
description: "AI for Wireless Communications & Signal Processing"
url: "https://Dennis966.github.io"   # this must match your repo URL
remote_theme: "mmistakes/minimal-mistakes"

# Enable features
search: true

# Author box
author:
  name: "Wen-Yuan (Dennis) Ting"
  avatar: "/assets/images/avatar.jpg"   # upload later if you want
  bio: "Research Assistant at Academia Sinica. Research in AI-for-wireless, GNN beamforming."
  location: "Taipei, Taiwan"
  links:
    - label: "CV"
      #url: "/assets/cv/WenYuan_Ting_CV.pdf"
    - label: "Google Scholar"
      #url: "https://scholar.google.com/..."
    - label: "GitHub"
      #url: "https://github.com/Dennis966"
    - label: "LinkedIn"
      #url: "https://www.linkedin.com/in/your-link/"
    - label: "YouTube"
      #url: "https://youtube.com/@yourchannel"

# Navigation bar
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
